[package]
name = "NativeSplash"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29"
softbuffer = "0.4" # Updated to fix raw-window-handle conflict
image = "0.25"
tiny-skia = "0.11"
bytemuck = "1.24"
fontdue = "0.7" # For text rendering
